- name: Install redis repo && install redis
  ansible.builtin.yum:
    name:
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      - redis
    state: present
    enablerepo: remi  
 
- name: Update Redis listener Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start Redis
  ansible.builtin.systemd: 
    name: redis
    state: restarted
    enabled: yes