- name: setup frontend
  hosts: frontend
  become: true
  tags: frontend
  roles:
    - frontend

- name: setup MongoDB
  hosts: mongodb
  become: true
  roles:
    - mongodb

- name: setup catalogue
  hosts: catalogue
  become: true
  roles:
    - catalogue

- name: setup redis
  hosts: redis
  become: true
  roles:
    - redis

- name: setup cart
  hosts: cart
  become: true
  roles:
    - cart

- name: setup user
  hosts: user
  become: true
  roles:
    - user

- name: setup mysql
  hosts: mysql
  become: true
  roles:
    - mysql

- name: setup shipping
  hosts: shipping
  become: true
  roles:
    - shipping    