- name: import NodeJs
  ansible.builtin.include_role:
    name: common
    task_from: nodejs

- name: start user service
  ansible.builtin.systemd:
    name: user
    state: restarted
    enabled: yes
    daemon_reload: yes