- name: setup Mysql repo & download mysql code from location in file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove a Mariadb package
  ansible.builtin.yum:
    name: mariadb-lib
    state: absent

- name: Install Mysql
  ansible.builtin.yum:
     name: 
      - mysql-community-server
      - MySQL-python
      - python36-PyMySQL
     state: present
     
- name: start Mysql
  ansible.builtin.systemd:
     name: mysqld
     state: started
     enabled: yes

- name: Grab default Pass
  ansible.builtin.shell:
    cmd: grep 'temporary Password' /vars/log/mysqld.log/awk '{print $NF}'
  register: DEFAULT_PASS

- name: Check the new password is working
  ansible.builtin.shell:
    cmd: echo 'show databases;'|mysql -uroot -p "{{NEW_PASSWORD}}"
  register: check_new_password

  ignore_errors: yes

- name: Copy Password reset sql file
  ansible.builtin.template:
    src: pass.sql
    dest: /tmp/pass.sql
  when: check_new_password.failed

- name: Reset Password
  ansible.builtin.shell:
    cmd: mysql --connect-expired-password -uroot -p "{{DEFAULT_PASSWORD.stdout}}" < /tmp/pass.sql
  when: check_new_password.failed    
  
- name: Download Schema
  ansible.builtin.include_role:
     name: common
     task_from: download
     
- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{NEW_PASSWORD}}"    

