- name : Include Download from Github 
  include_tasks: download-from-github.yml
  when : APP_VERSION is not defined

- name : Include Download from NEXUS_PASS
  include_tasks: download-from-nexus.yml
  when : APP_VERSION is defined