- name: Add app user roboshop
  ansible.builtin.user:
    name: roboshop
  when: APP_TYPE == "backend"  
  register: app_user_info

- name: Remove Existing Code
  ansible.builtin.file:
     path: "{{APP_LOCATION}}"
     state: absent
  when: APP_TYPE == "frontend" or APP_TYPE == "backend"   

- name: Create App Code
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: directory
  when: APP_TYPE == "frontend" or APP_TYPE == "backend"

- name: Download {{COMPONENT}} Code
  ansible.builtin.get_url:
    url: http://172.31.10.172:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp/{{COMPONENT}}.zip
    username: "{{NEXUS_USER}}"
    password: "{{NEXUS_PASS}}"

- name: Extract {{COMPONENT}} Code
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: "{{APP_LOCATION}}"
    remote_src: yes   