- name: Install NodeJs for {{COMPONENT}}
  ansible.builtin.yum:
    name: 
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Download Code
  ansible.builtin.include_code:
    name: common
    task_from: download
  vars:
    APP_LOCATION: "/home/roboshop/{{COMPONENT}}"
    APP_USER: roboshop

- name: Install NodeJs Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop    

- name: Include Systemd
  ansible.builtin.include_role:
    name: common
    task_from: systemd

