- name: Install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

- name: Download python
  ansible.builtin.include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: "/home/roboshop/{{COMPONENT}}"
    APP_USER: roboshop

- name: Install Python Dependencies
  ansible.builtin.pip:
     requirements: "/home/roboshop/{{COMPONENT}}/requirements.txt"
     executable: pip3

- name: print
  ansible.builtin.debug:
    msg: "{{app_user_info}}"

- name: Change UID in INI file
  ansible.builtin.lineinfile:
    path: "/home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini"
    regexp: "^uid"
    line: uid={{app_user_info.uid}}

- name:  Change guid in INI file
  ansible.builtin.lineinfile:
    path: "/home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini"
    regexp: "^gid"
    line: gid={{app_user_info.group}}

- name: Download Systemd
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd    